export const buildPaymentReceiptHTML = ({
    customerId,
    trackId,
    orderId,
    amount,
    currency,
    network,
    senderAddress,
    receiverAddress,
    txHash,
    confirmations,
    paidAt
  }) => `
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="UTF-8" />
    <title>Payment Receipt</title>
  </head>
  <body style="background:#f4f6f8;padding:20px;font-family:Arial,Helvetica,sans-serif;">
    <table width="100%" cellpadding="0" cellspacing="0">
      <tr>
        <td align="center">
          <table width="620" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:10px;overflow:hidden;">
            
            <!-- Header -->
            <tr>
              <td style="background:#0f9d58;padding:20px;color:#ffffff;">
                <h2 style="margin:0;">TeamCrypto</h2>
                <p style="margin:4px 0 0;">Payment Successful</p>
              </td>
            </tr>
  
            <!-- Success Badge -->
            <tr>
              <td align="center" style="padding:20px;">
                <div style="display:inline-block;padding:10px 20px;background:#e6f4ea;color:#0f9d58;border-radius:30px;font-weight:bold;">
                  ✓ Payment Confirmed
                </div>
              </td>
            </tr>
  
            <!-- Amount -->
            <tr>
              <td align="center">
                <h1 style="margin:10px 0;color:#0f9d58;">
                  ${amount} ${currency}
                </h1>
                <p style="color:#666;margin:0;">
                  Network: ${network}
                </p>
              </td>
            </tr>
  
            <!-- Details Table -->
            <tr>
              <td style="padding:20px;">
                <table width="100%" cellpadding="8" cellspacing="0" style="font-size:14px;">
                  <tr><td><b>Customer ID</b></td><td>${customerId}</td></tr>
                  <tr><td><b>Track ID</b></td><td>${trackId}</td></tr>
                  <tr><td><b>Order ID</b></td><td>${orderId}</td></tr>
                  <tr><td><b>Transaction Hash</b></td><td style="word-break:break-all;">${txHash}</td></tr>
                  <tr><td><b>Sender Address</b></td><td style="word-break:break-all;">${senderAddress}</td></tr>
                  <tr><td><b>Received Address</b></td><td style="word-break:break-all;">${receiverAddress}</td></tr>
                  <tr><td><b>Confirmations</b></td><td>${confirmations}</td></tr>
                  <tr><td><b>Date & Time</b></td><td>${paidAt}</td></tr>
                </table>
              </td>
            </tr>
  
            <!-- Footer -->
            <tr>
              <td style="background:#f8f9fa;padding:15px;text-align:center;font-size:12px;color:#666;">
                This is an automated receipt generated by TeamCrypto.<br/>
                If you did not authorize this transaction, contact support immediately.
              </td>
            </tr>
  
          </table>
        </td>
      </tr>
    </table>
  </body>
  </html>
  `;
  